import type { AuditRuleId, RuleExplanation } from '../types/repo';

export const ruleExplanations = {
  'readme-file': {
    checked: 'Checks whether a README file exists at the repository root.',
    why: 'The README is the first page most visitors read before deciding whether to try the project.',
    fix: 'Create README.md with the project purpose, demo, screenshots, setup, roadmap, and license.',
    priority: 'high',
    requirement: 'required',
    heuristic: false,
  },
  'demo-section': {
    checked: 'Looks for a Demo-style README section or common live demo URL text.',
    why: 'A demo lets students, users, and maintainers understand the project before cloning it.',
    fix: 'Add a Demo section with a hosted build, preview URL, or short recording link.',
    priority: 'medium',
    requirement: 'optional',
    heuristic: true,
  },
  'screenshots-section': {
    checked: 'Looks for a Screenshots, Preview, or Gallery section in the README.',
    why: 'Screenshots make the project shape visible even when the visitor cannot run it immediately.',
    fix: 'Add a Screenshots or Preview section and embed real project images from docs or assets.',
    priority: 'medium',
    requirement: 'optional',
    heuristic: true,
  },
  'features-section': {
    checked: 'Looks for a Features or Highlights section in the README.',
    why: 'A short feature list helps visitors understand the core value without reading the whole codebase.',
    fix: 'Add three to six bullets that describe what users can actually do with the project.',
    priority: 'medium',
    requirement: 'optional',
    heuristic: true,
  },
  'tech-stack-section': {
    checked: 'Looks for a Tech Stack, Built With, Technologies, or Stack section.',
    why: 'Clear technology notes help contributors judge whether they can work on the project.',
    fix: 'List the main language, framework, runtime, package manager, and build tool.',
    priority: 'optional',
    requirement: 'optional',
    heuristic: true,
  },
  'getting-started-section': {
    checked: 'Looks for a Getting Started, Installation, Setup, Quick Start, or Local Development section.',
    why: 'A project feels safer to try when the first local run path is visible.',
    fix: 'Add setup steps in order, including prerequisites and the first command to run the project.',
    priority: 'high',
    requirement: 'required',
    heuristic: true,
  },
  'readme-images': {
    checked: 'Checks for Markdown image syntax or inline img tags in the README.',
    why: 'Visual proof improves trust and helps people understand UI-heavy work quickly.',
    fix: 'Embed at least one real screenshot, gameplay image, diagram, or product preview.',
    priority: 'medium',
    requirement: 'optional',
    heuristic: true,
  },
  'install-commands': {
    checked: 'Looks for common npm, pnpm, yarn, or bun install and run commands in the README.',
    why: 'Copy-pasteable commands reduce setup friction for reviewers and contributors.',
    fix: 'Add commands such as npm install, npm run dev, npm run build, or the equivalent for this stack.',
    priority: 'high',
    requirement: 'required',
    heuristic: true,
  },
  'roadmap-section': {
    checked: 'Looks for a Roadmap, Future Work, or Next Steps section.',
    why: 'A roadmap shows the project is intentional and helps contributors choose useful work.',
    fix: 'Add a short realistic list of near-term improvements, known gaps, or planned releases.',
    priority: 'optional',
    requirement: 'optional',
    heuristic: true,
  },
  'license-section': {
    checked: 'Looks for a License section in the README.',
    why: 'Visitors should not have to search for usage terms when evaluating an open-source project.',
    fix: 'Add a License section that names the license and links to the LICENSE file.',
    priority: 'medium',
    requirement: 'optional',
    heuristic: true,
  },
  'repo-description': {
    checked: 'Checks whether GitHub repository metadata has a description.',
    why: 'The description appears in search results, cards, and repository lists.',
    fix: 'Write one sentence that names the audience, project type, and main benefit.',
    priority: 'medium',
    requirement: 'required',
    heuristic: false,
  },
  'repo-topics': {
    checked: 'Checks whether the repository has at least one GitHub topic.',
    why: 'Topics improve discovery and help visitors classify the repository quickly.',
    fix: 'Add language, framework, domain, and project-type topics that match the actual project.',
    priority: 'medium',
    requirement: 'optional',
    heuristic: false,
  },
  'repo-homepage': {
    checked: 'Checks whether GitHub repository metadata has a homepage URL.',
    why: 'A homepage or demo URL turns the repository from a code dump into something people can inspect.',
    fix: 'Set the homepage to the live demo, docs site, package page, or best public project URL.',
    priority: 'medium',
    requirement: 'optional',
    heuristic: false,
  },
  'license-file': {
    checked: 'Checks for a LICENSE, LICENSE.md, LICENSE.txt, or COPYING file.',
    why: 'Without a license file, others do not have clear permission to use or modify the code.',
    fix: 'Add a standard license file that matches your sharing intent, such as MIT or Apache-2.0.',
    priority: 'high',
    requirement: 'required',
    heuristic: false,
  },
  'package-json': {
    checked: 'Checks whether package.json exists at the repository root.',
    why: 'For JavaScript projects, package.json exposes scripts, dependencies, and package identity.',
    fix: 'Add package.json if this is a JavaScript project, or document the correct toolchain if it is not.',
    priority: 'medium',
    requirement: 'optional',
    heuristic: false,
  },
  'package-scripts': {
    checked: 'Checks package.json for dev, start, or build scripts.',
    why: 'Predictable scripts let local setup, CI, and reviewer checks use the same commands.',
    fix: 'Add clear scripts for development and production build, then document them in the README.',
    priority: 'medium',
    requirement: 'optional',
    heuristic: false,
  },
  'github-actions': {
    checked: 'Checks whether .github/workflows contains workflow files.',
    why: 'CI signals that changes are checked before they become part of the project.',
    fix: 'Add a GitHub Actions workflow that runs the relevant lint, test, or build commands.',
    priority: 'optional',
    requirement: 'optional',
    heuristic: false,
  },
  'contributing-guide': {
    checked: 'Checks for CONTRIBUTING.md or a README contribution section.',
    why: 'New contributors need a low-friction path for setup, issues, branches, and pull requests.',
    fix: 'Add a short contribution guide with setup, branch naming, issue, and PR expectations.',
    priority: 'optional',
    requirement: 'optional',
    heuristic: true,
  },
  'create-a-complete-readme': {
    checked: 'Triggered when the repository has no README file.',
    why: 'A missing README makes the repository hard to evaluate even if the code works.',
    fix: 'Create a README that covers purpose, demo, screenshots, features, setup, roadmap, and license.',
    priority: 'high',
    requirement: 'required',
    heuristic: false,
  },
  'add-reproducible-setup-commands': {
    checked: 'Triggered when the README exists but setup sections or install/run commands are missing.',
    why: 'Reviewers and contributors need to reproduce the project without guessing.',
    fix: 'Add exact install, run, build, and environment commands for the current project.',
    priority: 'high',
    requirement: 'required',
    heuristic: true,
  },
  'add-a-license-file': {
    checked: 'Triggered when no repository license file is detected.',
    why: 'Open-source usage permissions should be explicit, not implied.',
    fix: 'Add a standard LICENSE file and reference it from the README.',
    priority: 'high',
    requirement: 'required',
    heuristic: false,
  },
  'write-a-concise-repository-description': {
    checked: 'Triggered when the GitHub repository description is empty.',
    why: 'The description is the fastest way to explain the project in GitHub lists and previews.',
    fix: 'Add one direct sentence that names the project type, audience, and outcome.',
    priority: 'medium',
    requirement: 'required',
    heuristic: false,
  },
  'add-github-topics': {
    checked: 'Triggered when GitHub topics are missing.',
    why: 'Topics improve discoverability and give visitors context before they open the README.',
    fix: 'Add accurate topics for language, framework, domain, and project type.',
    priority: 'medium',
    requirement: 'optional',
    heuristic: false,
  },
  'expose-a-demo-link': {
    checked: 'Triggered when neither repository homepage nor README demo signal is found.',
    why: 'A live URL helps people inspect the result quickly, especially for apps, sites, and games.',
    fix: 'Deploy a public preview and add it to both GitHub homepage metadata and the README.',
    priority: 'medium',
    requirement: 'optional',
    heuristic: true,
  },
  'add-screenshots': {
    checked: 'Triggered when README image or screenshot signals are missing.',
    why: 'Screenshots give visual confidence and reduce the need to clone the project immediately.',
    fix: 'Capture real screenshots and embed them in the README from a tracked docs or assets folder.',
    priority: 'medium',
    requirement: 'optional',
    heuristic: true,
  },
  'make-project-commands-obvious': {
    checked: 'Triggered when package.json or common dev/build scripts are missing.',
    why: 'Clear scripts make local work and automated checks easier to repeat.',
    fix: 'Add or document the project commands, especially dev, build, preview, lint, or test.',
    priority: 'medium',
    requirement: 'optional',
    heuristic: false,
  },
  'add-a-ci-workflow': {
    checked: 'Triggered when no GitHub Actions workflow files are detected.',
    why: 'CI gives contributors and maintainers confidence that the basic project checks still pass.',
    fix: 'Add a small workflow that runs the project install, lint, test, or build commands.',
    priority: 'optional',
    requirement: 'optional',
    heuristic: false,
  },
  'document-the-roadmap': {
    checked: 'Triggered when roadmap-style README signals are missing.',
    why: 'A roadmap shows project direction and makes useful help easier to identify.',
    fix: 'Add a short Roadmap or Next Steps section with concrete near-term items.',
    priority: 'optional',
    requirement: 'optional',
    heuristic: true,
  },
  'add-contribution-guidance': {
    checked: 'Triggered when no contribution file or README contribution signal is found.',
    why: 'Even a small guide reduces uncertainty for first-time contributors.',
    fix: 'Add CONTRIBUTING.md or a README section covering setup, issues, branches, and PRs.',
    priority: 'optional',
    requirement: 'optional',
    heuristic: true,
  },
} satisfies Record<AuditRuleId, RuleExplanation>;

export function getRuleExplanation(ruleId: AuditRuleId): RuleExplanation {
  return ruleExplanations[ruleId];
}
